# Generated by Django 4.0.3 on 2022-06-07 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('enunciado', models.CharField(max_length=1000)),
                ('respuesta1', models.CharField(max_length=50)),
                ('respuesta2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameField(
            model_name='roles',
            old_name='nombreRol',
            new_name='nombre_rol',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='apellidoMaterno',
            new_name='apellido_materno',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='apellidoPaterno',
            new_name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='last login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Usuario_Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('respuesta', models.CharField(max_length=50, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ejercicios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.clases')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='tecnologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tecnologias'),
        ),
        migrations.AddField(
            model_name='clases',
            name='tecnologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tecnologias'),
        ),
    ]
