# Generated by Django 4.0.3 on 2022-06-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_clases_descripcion_alter_clases_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_clase',
            name='tiempo',
            field=models.IntegerField(null=True),
        ),
    ]
