# Generated by Django 4.0.3 on 2022-07-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_usuario_clase_tiempo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='nombre_rol',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='apellido_materno',
            new_name='materno',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='apellido_paterno',
            new_name='paterno',
        ),
    ]
