# Generated by Django 4.0.3 on 2022-06-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_clases_ejercicios_tecnologias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_ejercicio',
            name='tiempo',
            field=models.IntegerField(null=True),
        ),
    ]
