# Generated by Django 4.0.3 on 2022-06-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_usuario_ejercicio_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases',
            name='descripcion',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='clases',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='enunciado',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
